<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Prime</name>
   <tag></tag>
   <elementGuidId>961e67c8-9939-4581-a61c-938c077e0567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-link-amazonprime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-link-amazonprime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>788aaeb8-d278-4e0a-8392-999dfd2c609b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/prime?ref_=nav_cs_primelink_nonmember</value>
      <webElementGuid>bc775f28-335d-4294-83fb-b81261cbcf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a nav-active</value>
      <webElementGuid>94884e19-34d2-4174-a3c4-c9a774d93f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ux-jq-mouseenter</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b47dab4d-b54c-4d8e-b4ef-755d3fae6756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-link-amazonprime</value>
      <webElementGuid>835ef36a-3607-450c-83f4-81cf21261f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>603863fd-895e-4a6a-bc58-d705d1fecef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>6f4d6127-9575-4840-8907-36a5739a1fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav-link-amazonprime</value>
      <webElementGuid>ddf49d79-ce5c-4409-9e3a-6eaa597ae93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_primelink_nonmember</value>
      <webElementGuid>4d445ddf-2ba6-4fdc-addf-77f670ff1d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>k72unf-wzh3cf-spl7bi-ffc2tn</value>
      <webElementGuid>1d3da3b8-7a38-4aea-bcb8-23ff1e3d4b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prime</value>
      <webElementGuid>7b7d4a43-41dd-46ad-b36e-435364a3b876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-link-amazonprime&quot;)</value>
      <webElementGuid>5a8b36dd-0a19-46c6-9c15-9db18694016c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-link-amazonprime']</value>
      <webElementGuid>f7130df4-e450-4f91-8dc7-a8959b38ce41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[9]</value>
      <webElementGuid>3997c2db-a6a9-4733-a9b7-539ed7e0a9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/prime?ref_=nav_cs_primelink_nonmember')]</value>
      <webElementGuid>72175fdb-e342-4848-bbe1-11bc58eadc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/a[9]</value>
      <webElementGuid>cde14f2c-cfae-4c4f-8d05-cfff59f261fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/prime?ref_=nav_cs_primelink_nonmember' and @id = 'nav-link-amazonprime' and (text() = 'Prime' or . = 'Prime')]</value>
      <webElementGuid>a2075664-32ef-42f1-8e85-01c58bf20e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
